checks:
    javascript: true
filter:
    excluded_paths:
        - tests/*
        - template/
        - '*.min.js'
build:
    environment:
      node: v8.12.0
    tests:
        before:
            - 'npm install -g yarn'
            - 'yarn global add istanbul coveralls mocha'
            - 'yarn install'
        override:
          -
            command: 'yarn run cover && js-scrutinizer-run'
            coverage:
              file: 'coverage/clover.xml'
              format: 'clover'
