checks:
    javascript: true
filter:
    excluded_paths:
        - tests/*
        - template/
        - '*.min.js'
build:
    environment:
      node: v8.12.0
    tests:
        before:
            - 'npm install -g istanbul coveralls mocha'
            - 'npm install'
        override:
          -
            command: 'npm run cover'
            coverage:
              file: 'coverage/clover.xml'
              format: 'clover'
